library("dplyr")
library("plotly")
library("RColorBrewer")
library("rCharts")
options(repr.plot.width = 7)
options(repr.plot.height = 5)
options(jupyter.rich_display = FALSE)
options(width = 120)

marzec20_JC<-read.csv("JC-202003-citibike-tripdata.csv")
marzec19_JC<-read.csv("JC-201903-citibike-tripdata.csv")
marzec18_JC<-read.csv("JC-201803-citibike-tripdata.csv")
m18<-group_by(marzec18_JC,birth.year)
m18<-tally(m18)
m18<-rename(m18,wynik1=n)
m19<-group_by(marzec19_JC,birth.year)
m19<-tally(m19)
m19<-rename(m19,wynik2=n)
m20<-group_by(marzec20_JC, birth.year)
m20<-tally(m20)
m20<-rename(m20,wynik3=n)
x<-full_join(m19,m20,by=c("birth.year"="birth.year"))
x<-full_join(m18,x,by=c("birth.year"="birth.year"))
x<-mutate(x,wynik1=ifelse(is.na(wynik1),0,wynik1))
x<-mutate(x,wynik2=ifelse(is.na(wynik2),0,wynik2))
x<-mutate(x,wynik3=ifelse(is.na(wynik3),0,wynik3))
rok_urodzenia<-select(x,birth.year)
marzec_2018<-select(x,wynik1)
marzec_2019<-select(x,wynik2)
marzec_2020<-select(x,wynik3)

m1<-mPlot(x="birth.year",y=c("wynik1","wynik2","wynik3"),type="Line",
          data=x,pointSize=0, lineWidth=2)
m1